# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'TechnologyToShare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Category'
  pod 'AFNetworking'
  pod 'WMPageController'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'YYCache'
  pod 'Masonry'

  # Pods for TechnologyToShare

end
